services:
  postgres-db:
    image: "postgres:14.2"
    ports:
      - 4200:4200
    restart: always
    environment:
      - POSTGRES_DB=tribal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    driver: local
